/*

 HEART.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char heart[] =
{
  0x00,0x30,0x00,0x30,0x07,0x60,0x04,0x78,
  0x00,0x60,0x00,0x40,0x00,0x40,0x00,0x60,
  0x00,0x00,0x00,0x00,0x00,0x6C,0x68,0x92,
  0x38,0x44,0x10,0x28,0x00,0x10,0x00,0x00
};

/* End of HEART.C */
